export const GET_ITEMS_BEGIN = 'GET_ITEMS_BEGIN';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';

export const GET_CUSTOMERS_BEGIN = 'GET_CUSTOMERS_BEGIN';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
export const ADD_CUSTOMER_TO_CART = 'ADD_CUSTOMER_TO_CART';

export const CALL_TAX_API = 'CALL_TAX_API';
export const CLEAN = 'CLEAN';
